//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCart.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long id { get; set; }
        public Nullable<long> order_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<long> account_id { get; set; }
        public string username { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public System.DateTime payment_date { get; set; }
        public string payment_number { get; set; }
        public string payment_method { get; set; }
        public decimal total { get; set; }
        public bool success { get; set; }
        public string message { get; set; }
        public string transaction_number { get; set; }
        public string authorization_code { get; set; }
        public string ip_address { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<double> sort_order { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> portal_id { get; set; }
    
        internal virtual Order order { get; set; }
    }
}
