//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long ID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> AccountID { get; set; }
        public string Username { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentNumber { get; set; }
        public string PaymentMethod { get; set; }
        public decimal Total { get; set; }
        public bool Success { get; set; }
        public string Message { get; set; }
        public string TransactionNumber { get; set; }
        public string AuthorizationCode { get; set; }
        public string IPAddress { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<double> SortOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByUser { get; set; }
        public Nullable<int> PortalID { get; set; }
    
        private Order Order { get; set; }
    }
}
